version: 0.2

phases:
    commands:
    - rm package-lock.json
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
    - npm --version
  pre_build:
    commands:
    - npm install --silent --no-progress
    - npm install jest
    - npm install jest-junit 
  build:
    commands:
    - npm run-script lint
    - npm test
   


  
          
reports:
  jest_report:
    files:
       - '**/*'
    file-format: JUNITXML
    base-directory: test
