version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - npm install --save-dev jest
    - npm install jest-junit 
  pre_build:
    commands:
    - mkdir -p test
 
  build:
    commands:
    - npm run-script lint
    - npm test
    - npm test --coverage 

          
reports:
  jest_report:
    files:
       - '**/*'
    file-format: JUNITXML
    base-directory: test
