version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - npm install --save-dev jest
    - npm install jest-junit 
  pre_build:
    commands:
    - mkdir -p test
    - mkdir -p coverage
 
  build:
    commands:
    - npm test
    - npm test -- --coverage 
  artifacts:
    files:
       - '**/*'

        
    
reports:
  codecoverage:
    files:
      - '**/*'
    file-format: 'JACOCOXML'
    base-directory: test 
